name 'HERE'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures HERE'
long_description 'Installs/Configures HERE'
version '0.1.0'
chef_version '>= 14.0'
depends 'tomcat', '~> 5.0.19'
depends 'java'#, '8.0.0'
delends 'line'